### PR TITLE
Added new stf segment

### PR DESCRIPTION
**Pull request by 360disrupt**
according to http://www.mexi.be/documents/hl7/ch800018.htm

### CODE REVIEW

**Comment by evanlucas** [comment]
I personally haven't used the STF segment, but from googling around, it looks like there are some additional fields to it?

http://hl7api.sourceforge.net/v251/apidocs/ca/uhn/hl7v2/model/v251/segment/STF.html

What are your thoughts on adding those additional fields?

**Comment by 360disrupt** [comment]
Ok, I added the other fields, I also removed the white spaces. I didn't know that there is a newer source which show these hl7 fields.

**Comment by evanlucas** [comment]
awesome thanks!

Mind handling a few nits for me?

1. Please add `'use strict'` the top of the file
2. Please remove the comment at the top (trying to stay consistent)
3. Please make sure that the file ends in a new line.

Thanks!

**Comment by 360disrupt** [comment]
Ok done. I had the old version where the comments still were above the segments. Just wondering is the newline at the end of the document not a whitespace error.
```
 By default, trailing whitespaces (including lines that solely consist of whitespaces) and a space character that is immediately followed by a tab character inside the initial indent of the line are considered whitespace errors.
```
https://www.kernel.org/pub/software/scm/git/docs/git-apply.html

**Comment by evanlucas** [comment]
Thanks! No, the newline at the end of the file is just a style preference I have.

**Comment by evanlucas** [comment]
published as v4.1.0. Thanks again!

**Pull request merged**
