### PR TITLE
Update pv1.js

### PR DESCRIPTION
**Pull request by 360disrupt**
Patient Class `PV1-2: Patient Class (IS)` is missing. Thus all following fields are parsed wrong.
http://hl7api.sourceforge.net/v251/apidocs/ca/uhn/hl7v2/model/v251/segment/PV1.html

### CODE REVIEW

**Comment by evanlucas** [comment]
Is it in HL7 v2.3.1? That is what we are currently adhering to

**Comment by 360disrupt** [comment]
Yes, see also here:
http://hl7-definition.caristix.com:9010/HL7%20v2.3.1/segment/PV1

**Comment by evanlucas** [comment]
Thanks!

**Comment by evanlucas** [comment]
Released in v4.1.8

**Pull request merged**
